-- Aktivieren der btree_gist Erweiterung
CREATE EXTENSION IF NOT EXISTS btree_gist;

-- Erstellen der temporalen Tabelle
CREATE TABLE employee (
    PerNo INTEGER NOT NULL,
    Vorname TEXT NOT NULL,
    Nachname TEXT NOT NULL,
    Position TEXT NOT NULL,
    Gehalt NUMERIC(10, 2) NOT NULL,
    Abteilung TEXT NOT NULL,
    emp_row_id BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    emp_ts TIMESTAMPTZ NOT NULL,
    emp_te TIMESTAMPTZ NOT NULL,
    EXCLUDE USING GIST (PerNo WITH =, tstzrange(emp_ts, emp_te) WITH &&)
);
